services:
  ichgram:
    build:
      context: ./server
      # dockerfile: ./server/Dockerfile
    container_name: ichgram
    ports:
      - "3000:3000"
      # - "5005:5005"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./server/.env:/app/.env

  frontichgram:
    build:
      context: ./client
      # dockerfile: ./client/Dockerfile
    container_name: frontichgram
    ports:
      - "5173:5173"
    depends_on:
      - ichgram
  mongodb:
    container_name: mongo-database
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27018:27017"
    command: --bind_ip 0.0.0.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      # MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    env_file:
      - ./server/.env
    volumes:
      - ./data/db:/data/db

volumes:
  mongo-data:
